name: Deployment

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  

      - name: Install dependencies
        run: make install  
        
      - name: Set up Git user dynamically
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Build
        run: make build  

      - name: Deploy
        run: make deploy-alt
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }} 